### ISSUE TITLE
The application shall contain fundamental features and be dockerized and deployed until milestone #2

### ISSUE THREAD

**Issue by emreberk92** [emreberk92/SWE573---SOFTWARE-DEVELOPMENT-PRACTICE#21]
At the moment, set profile doesn't save the user input, and therefore doesn't display the user features. Moreover, setting menu should be created and search bar should be functional.

**Comment by emreberk92** [comment]
The fundamental features below to be added to the model. Below the completed features can be seen.

- [ ] Login with registration
- [ ] Sharing post including an attachment such as image, video etc.
- [ ] Like other post and display total likes
- [ ] User profile with bio and location
- [ ] Searhcing other users
- [ ] Following other users

**Comment by emreberk92** [comment]
Dockerization has been investigated, but I failed to implement. I need further digging and to watch more tutorials. In worst case, help to be requested.

**Comment by emreberk92** [comment]
The dockerization and deployment has also been performed successfully. The code has been updated. Please chech the below wiki page to see the details:

[https://github.com/emreberk92/SWE573---SOFTWARE-DEVELOPMENT-PRACTICE/wiki/3.-Social-Bookmarking-Application#dockerization](url)
