### ISSUE TITLE
The application shall contain the feature: comment others' post until milestone #3

### ISSUE THREAD

**Issue by emreberk92** [emreberk92/SWE573---SOFTWARE-DEVELOPMENT-PRACTICE#28]
- [ ] Create an object in the model
- [ ] Make the migration
- [ ] Use the created object in the views.py
- [ ] Use the created object in the index.html
- [ ] Test the functionality

**Comment by emreberk92** [comment]
This works using the admin panel, but in application there is a problem to add the written comment to the comment sections.
